name: Deploy to Google Cloud Storage

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-gcs.yml'
      - 'src/**'      

defaults:
  run:
    shell: bash

jobs:
  deploy-gcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCS_CREDENTIALS }}

      - name: Setup gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v0

      - name: Write commit SHA to file
        run: echo "${{ github.sha }}" >> src/sha.txt

      - name: Publish repo contents
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        run: |
          gsutil -m rsync -r src gs://$GCS_BUCKET
