name: Netlify site preview

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  site-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Deploy Preview to Netlify
      run: |
        netlify deploy \
          --dir="src" \
          --alias="gtfs-calitp-org-${{ github.event.number }}"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_APP_SITE_ID }}

    - name: Add netlify link PR comment
      uses: actions/github-script@v6
      with:
        script: |
          const hostnameSuffix = "cal-itp-previews.netlify.app"
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Preview url: https://gtfs-calitp-org-${{ github.event.number }}--${hostnameSuffix}`,
          })
