name: Netlify site preview

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  site-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v5

    - name: Install Netlify CLI
      run: npm install -g netlify-cli@17.x.x

    - name: Deploy Preview to Netlify
      run: |
        netlify deploy \
          --alias="gtfs-calitp-org-${{ github.event.number }}" \
          --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
          --dir="src" \
          --site=${{ secrets.NETLIFY_PREVIEW_APP_SITE_ID }}

    - name: Add netlify link PR comment
      uses: actions/github-script@v7
      with:
        script: |
          const hostnameSuffix = "cal-itp-previews.netlify.app"
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Preview url: https://gtfs-calitp-org-${{ github.event.number }}--${hostnameSuffix}`,
          })
